EPISODES = [
    {"sequence_number": 1, "episode_name": "Birth of Rama and Brothers", "kanda": "Bala", "sarga_start": 8, "sarga_end": 18, "story_phase": "Early Life of Rama"},
    {"sequence_number": 2, "episode_name": "Early Life of Rama", "kanda": "Bala", "sarga_start": 18, "sarga_end": 22, "story_phase": "Early Life of Rama"},
    {"sequence_number": 3, "episode_name": "Vishvamitra's Arrival", "kanda": "Bala", "sarga_start": 19, "sarga_end": 22, "story_phase": "Early Life of Rama"},
    {"sequence_number": 4, "episode_name": "Tadka Wadh", "kanda": "Bala", "sarga_start": 23, "sarga_end": 27, "story_phase": "Early Life of Rama"},
    {"sequence_number": 5, "episode_name": "Ahalya's Redemption", "kanda": "Bala", "sarga_start": 48, "sarga_end": 50, "story_phase": "Early Life of Rama"},
    {"sequence_number": 6, "episode_name": "Marriage to Sita", "kanda": "Bala", "sarga_start": 66, "sarga_end": 73, "story_phase": "Early Life of Rama"},
    {"sequence_number": 7, "episode_name": "Parashuram's Challenge", "kanda": "Bala", "sarga_start": 74, "sarga_end": 77, "story_phase": "Early Life of Rama"},
    {"sequence_number": 8, "episode_name": "Kaikeyi's Demands", "kanda": "Ayodhya", "sarga_start": 7, "sarga_end": 13, "story_phase": "Exile Phase"},
    {"sequence_number": 9, "episode_name": "Rama Accepts Exile", "kanda": "Ayodhya", "sarga_start": 14, "sarga_end": 24, "story_phase": "Exile Phase"},
    {"sequence_number": 10, "episode_name": "Departure from Ayodhya", "kanda": "Ayodhya", "sarga_start": 25, "sarga_end": 50, "story_phase": "Exile Phase"},
    {"sequence_number": 11, "episode_name": "Dasharath's Death", "kanda": "Ayodhya", "sarga_start": 57, "sarga_end": 65, "story_phase": "Exile Phase"},
    {"sequence_number": 12, "episode_name": "Ram Meets Bharat (Chitrakoot)", "kanda": "Ayodhya", "sarga_start": 66, "sarga_end": 119, "story_phase": "Exile Phase"},
    {"sequence_number": 13, "episode_name": "Forest Life Begins", "kanda": "Aranya", "sarga_start": 1, "sarga_end": 16, "story_phase": "Exile Phase"},
    {"sequence_number": 14, "episode_name": "Shurpanakha Proposal", "kanda": "Aranya", "sarga_start": 17, "sarga_end": 21, "story_phase": "Sita Haran"},
    {"sequence_number": 15, "episode_name": "Khara-Dushana Vadh", "kanda": "Aranya", "sarga_start": 22, "sarga_end": 30, "story_phase": "Sita Haran"},
    {"sequence_number": 16, "episode_name": "Maricha's Golden Deer", "kanda": "Aranya", "sarga_start": 31, "sarga_end": 44, "story_phase": "Sita Haran"},
    {"sequence_number": 17, "episode_name": "Sita Haran", "kanda": "Aranya", "sarga_start": 45, "sarga_end": 49, "story_phase": "Sita Haran"},
    {"sequence_number": 18, "episode_name": "Jatayu's Sacrifice", "kanda": "Aranya", "sarga_start": 50, "sarga_end": 68, "story_phase": "Search for Sita"},
    {"sequence_number": 19, "episode_name": "Shabari Episode", "kanda": "Aranya", "sarga_start": 69, "sarga_end": 75, "story_phase": "Search for Sita"},
    {"sequence_number": 20, "episode_name": "Hanuman Meets Ram", "kanda": "Kishkindha", "sarga_start": 1, "sarga_end": 4, "story_phase": "Search for Sita"},
    {"sequence_number": 21, "episode_name": "Friendship with Sugriv", "kanda": "Kishkindha", "sarga_start": 5, "sarga_end": 7, "story_phase": "Search for Sita"},
    {"sequence_number": 22, "episode_name": "Ram Kills Bali, Sugriv Becomes King", "kanda": "Kishkindha", "sarga_start": 8, "sarga_end": 26, "story_phase": "Search for Sita"},
    {"sequence_number": 23, "episode_name": "Sita Ki Khoj (Search Begins)", "kanda": "Kishkindha", "sarga_start": 27, "sarga_end": 67, "story_phase": "Search for Sita"},
    {"sequence_number": 24, "episode_name": "Hanuman Crosses the Sea", "kanda": "Sundara", "sarga_start": 1, "sarga_end": 4, "story_phase": "Search for Sita"},
    {"sequence_number": 25, "episode_name": "Hanuman Meets Sita in Ashok Vatika", "kanda": "Sundara", "sarga_start": 5, "sarga_end": 40, "story_phase": "Search for Sita"},
    {"sequence_number": 26, "episode_name": "Lanka Dahan", "kanda": "Sundara", "sarga_start": 41, "sarga_end": 54, "story_phase": "Search for Sita"},
    {"sequence_number": 27, "episode_name": "Hanuman Leaves Lanka", "kanda": "Sundara", "sarga_start": 55, "sarga_end": 68, "story_phase": "Search for Sita"},
    {"sequence_number": 28, "episode_name": "Vibhishan Comes to Sri Ram", "kanda": "Yuddha", "sarga_start": 1, "sarga_end": 19, "story_phase": "Lanka War"},
    {"sequence_number": 29, "episode_name": "Rama Setu Bandhan", "kanda": "Yuddha", "sarga_start": 20, "sarga_end": 23, "story_phase": "Lanka War"},
    {"sequence_number": 30, "episode_name": "Angad as Dut", "kanda": "Yuddha", "sarga_start": 31, "sarga_end": 41, "story_phase": "Lanka War"},
    {"sequence_number": 31, "episode_name": "Lanka War Begins", "kanda": "Yuddha", "sarga_start": 42, "sarga_end": 43, "story_phase": "Lanka War"},
    {"sequence_number": 32, "episode_name": "Nagpasha", "kanda": "Yuddha", "sarga_start": 44, "sarga_end": 50, "story_phase": "Lanka War"},
    {"sequence_number": 33, "episode_name": "Kumbhakarna Vadh", "kanda": "Yuddha", "sarga_start": 51, "sarga_end": 67, "story_phase": "Lanka War"},
    {"sequence_number": 34, "episode_name": "Lakshman Injured by Shakti", "kanda": "Yuddha", "sarga_start": 68, "sarga_end": 73, "story_phase": "Lanka War"},
    {"sequence_number": 35, "episode_name": "Hanuman Goes to Himalaya (Sanjeevani)", "kanda": "Yuddha", "sarga_start": 74, "sarga_end": 75, "story_phase": "Lanka War"},
    {"sequence_number": 36, "episode_name": "Meghnad Vadh", "kanda": "Yuddha", "sarga_start": 76, "sarga_end": 91, "story_phase": "Lanka War"},
    {"sequence_number": 37, "episode_name": "Death of Ravan", "kanda": "Yuddha", "sarga_start": 92, "sarga_end": 108, "story_phase": "Lanka War"},
    {"sequence_number": 38, "episode_name": "Vibhishan's Coronation", "kanda": "Yuddha", "sarga_start": 109, "sarga_end": 112, "story_phase": "Return and Reunion"},
    {"sequence_number": 39, "episode_name": "Agni Pariksha", "kanda": "Yuddha", "sarga_start": 113, "sarga_end": 120, "story_phase": "Return and Reunion"},
    {"sequence_number": 40, "episode_name": "Return and Reunion (Coronation)", "kanda": "Yuddha", "sarga_start": 121, "sarga_end": 128, "story_phase": "Return and Reunion"},
]
